[project]
name = "multi-modal-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.0.15",
    "numpy>=2.3.1",
    "scikit-learn>=1.7.0",
    "sentence-transformers>=5.0.0",
]
